services:
  - type: web
    name: brain_backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn brain_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: brain_backend.settings
